### ISSUE TITLE
Expand the purge-backup command to allow for processing a folder of DATs

### ISSUE THREAD

**Issue by Obiwantje** [uwedeportivo/romba#115] opened 2015-12-02 23:59 UTC
Similar to the build command that allow both for building a single DAT as well as a folder of DATs - please enhance the purge-backup command to process a folder with DATs in addition to the currently implemented functionality to process a single DAT via the "dat=" option

**Comment by uwedeportivo** [comment] 2015-12-05 20:07
duplicate of #100

**Closed by uwedeportivo** 2015-12-05 20:07 UTC
Labels: enhancement
